import type { SimScript } from '@/lib/sim/script'

/**
 * SIM-5 — a scheduled job, from sentence to delivered message.
 *
 * The payload is the last line of the delivery wrapper. In prose it reads as a
 * footnote; arriving at the end of a message the reader has just watched being
 * generated, it lands as the constraint it actually is — the thing on the other end
 * of a cron job is a broadcast, not a conversation.
 *
 * Every frame is quoted from the cron documentation and the daily-briefing tutorial.
 * They are separate published examples matched on the 9am schedule rather than one
 * captured run, and the replay says so in place instead of implying continuity it
 * cannot source. The `cron list` table in particular is the tutorial's own, listing
 * that tutorial's jobs — its value is the columns, not the rows.
 */
export const script: SimScript = {
  id: 'a-job-that-fires-at-nine',
  title: 'A job that fires at nine',
  premise:
    'A sentence becomes a scheduled job. Watch what arrives when it fires, and read the last line of it.',
  fidelity: 'verbatim',
  source:
    'Creation surfaces, the tool call, the cron list table, the delivery wrapper and the storage paths quoted from the cron documentation and the daily-briefing tutorial, v0.19.0. The briefing body is the tutorial\'s own worked illustration, not a captured run. Frames are matched on the 9am schedule; the sequence is assembled.',
  hermesVersion: 'v0.19.0',
  events: [
    { t: 'marker', id: 'ask', label: 'Asking in English' },
    {
      t: 'user',
      text: 'Every morning at 9am, check Hacker News for AI news and send me a summary on Telegram.',
    },
    {
      t: 'note',
      text: 'There is no syntax to learn here. The chat form and the CLI form exist too — /cron add "every 2h" "…" and hermes cron create — but the sentence is the surface most people use, and it becomes exactly the same tool call.',
    },

    { t: 'marker', id: 'call', label: 'What the sentence becomes' },
    { t: 'think', text: '(｡•́︿•̀｡) pondering...' },
    {
      t: 'result',
      name: 'cronjob',
      output: `cronjob(
    action="create",
    skill="blogwatcher",
    prompt="Check the configured feeds and summarize anything new.",
    schedule="0 9 * * *",
    name="Morning feeds",
)`,
      ms: 1000,
    },
    {
      t: 'say',
      text: 'Scheduled. It will run every morning at 9 and deliver to Telegram.',
    },

    { t: 'marker', id: 'list', label: 'Confirming it exists' },
    { t: 'user', text: 'hermes cron list' },
    {
      t: 'result',
      name: 'terminal',
      output: `ID          | Name              | Schedule    | Next Run           | Deliver
------------|-------------------|-------------|--------------------|--------
a1b2c3d4    | Morning Briefing  | 0 8 * * *   | 2026-03-09 08:00   | telegram
e5f6g7h8    | Evening Recap     | 0 18 * * *  | 2026-03-08 18:00   | telegram`,
      ms: 800,
    },
    {
      t: 'note',
      text: 'That table is the documentation\'s own, and it lists the tutorial\'s two jobs rather than the one just created — the guide does not fabricate a row to make the sequence tidier. What to take from it is the columns: Next Run tells you the schedule parsed the way you meant, and Deliver tells you where the output goes.',
    },

    { t: 'marker', id: 'tick', label: 'The tick' },
    {
      t: 'note',
      text: 'The scheduler ticks every sixty seconds inside the gateway daemon. If the gateway is not running, nothing fires — a scheduled job is not a system service unless you installed one.',
    },
    { t: 'wait', ms: 1400 },
    {
      t: 'memory',
      layer: 'session',
      note: 'The job runs in a fresh session. It has the two memory files and the skill it was given, and nothing from any conversation you have had.',
    },

    { t: 'marker', id: 'delivered', label: 'What arrives' },
    {
      t: 'result',
      name: 'telegram',
      output: `Cronjob Response: Morning feeds
-------------

☀️ Your AI Briefing — March 8, 2026

1. Qwen 3 Released with 235B Parameters
   Alibaba's latest open-weight model matches GPT-4.5 on several
   benchmarks while remaining fully open source.
   → https://qwenlm.github.io/blog/qwen3/

2. LangChain Launches Agent Protocol Standard
   A new open standard for agent-to-agent communication gains
   adoption from 15 major frameworks in its first week.
   → https://blog.langchain.dev/agent-protocol/

3. EU AI Act Enforcement Begins for General-Purpose Models
   The first compliance deadlines hit, with open source models
   receiving exemptions under the 10M parameter threshold.
   → https://artificialintelligenceact.eu/updates/

---
3 stories • Sources searched: 8 • Generated by Hermes Agent

Note: The agent cannot see this message, and therefore cannot respond to it.`,
      ms: 2200,
    },
    {
      t: 'note',
      text: 'That last line is the most consequential sentence in cron, and it is easy to read past. Replying to this message does not reach the agent that wrote it — that session is over. You are reading a broadcast. Turning the wrapper off with cron.wrap_response: false removes the sentence but not the fact.',
    },
  ],
}
