import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import { MDXContent } from '@content-collections/mdx/react'
import { getLesson, isWritten, lessons, neighbours, prerequisitesOf } from '@/lib/content'
import { mdxComponents } from '@/components/mdx'
import { Page } from '@/components/ui/page'
import { getModule } from '@/lib/content'
import { jsonLd, lessonSchema } from '@/lib/schema'
import { LessonProgress } from '@/components/personalization/lesson-progress'
import { SectionIndex } from '@/components/lesson/section-index'
import { curriculumGraph } from '@/lib/curriculum-graph'
import { ancestorsOf, descendantsOf } from '@/lib/graph'

// This route tree serves one guide. A second guide gets its own directory, which
// keeps its URLs short and its static params independent. Every lesson URL is
// known at build time; anything else 404s at build rather than at runtime.
const GUIDE = 'hermes'

export const dynamicParams = false

export function generateStaticParams() {
  return lessons
    .filter((lesson) => lesson.guideSlug === GUIDE)
    .map((lesson) => ({ module: lesson.moduleSlug, lesson: lesson.slug }))
}

type Params = Promise<{ module: string; lesson: string }>

export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> {
  const { module: moduleSlug, lesson: lessonSlug } = await params
  const lesson = getLesson(GUIDE, moduleSlug, lessonSlug)
  if (!lesson) return {}

  return {
    title: lesson.title,
    description: lesson.description,
    openGraph: {
      title: lesson.title,
      description: lesson.description,
      type: 'article',
      // Generated by scripts/build-og.mjs into public/og/ before the build copies it.
      images: [
        { url: `/og/${lesson.moduleSlug}--${lesson.slug}.png`, width: 1200, height: 630 },
      ],
    },
  }
}

export default async function LessonPage({ params }: { params: Params }) {
  const { module: moduleSlug, lesson: lessonSlug } = await params
  const lesson = getLesson(GUIDE, moduleSlug, lessonSlug)
  if (!lesson) notFound()

  const { previous, next } = neighbours(lesson)
  const prerequisites = prerequisitesOf(lesson)
  const parentModule = getModule(GUIDE, moduleSlug)

  // Where this lesson sits in the real dependency graph, not in a flat count.
  const at = curriculumGraph.nodes.findIndex((node) => node.id === lesson.id)
  const place = {
    index: at + 1,
    total: curriculumGraph.nodes.length,
    behind: at === -1 ? 0 : ancestorsOf(curriculumGraph, at).size,
    ahead: at === -1 ? 0 : descendantsOf(curriculumGraph, at).size,
  }

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={jsonLd(lessonSchema(lesson, parentModule))}
      />
    <Page
      aside={
        /*
         * The margin, doing work.
         *
         * It used to hold four short facts and then several hundred pixels of
         * nothing, which is how a reading layout ends up looking like a document
         * with a parking space beside it. It now carries the three things a reader
         * mid-lesson actually wants and cannot get from the prose: where they are
         * inside this lesson, where this lesson sits in the course, and what it was
         * checked against. Sticky, so all of that stays with them.
         */
        <div className="vt-rail lg:sticky lg:top-[calc(var(--step)*3)] lg:max-h-[calc(100dvh-var(--step)*5)] lg:overflow-y-auto">
          <SectionIndex headings={lesson.headings} />

          <div className="mt-[var(--step)] border-t border-ice-faint pt-[calc(var(--step)*0.6)]">
            <LessonProgress id={lesson.id} />
          </div>

          {/*
            Position in the course, from the prerequisite graph rather than from a
            counter. "Eight lessons come before this" is what it costs to be here;
            "twenty-two build on it" is what it is worth having read — a claim a
            table of contents cannot make and this curriculum can, because the
            dependencies are real data.
          */}
          <dl className="mt-[var(--step)] space-y-[calc(var(--step)*0.45)] border-t border-ice-faint pt-[calc(var(--step)*0.6)] font-mono text-[0.7rem] text-ice-dim">
            <div>
              <dt>Position</dt>
              <dd className="text-ice">
                {place.index} of {place.total} · module {lesson.moduleNumber}
              </dd>
            </div>
            {place.behind > 0 && (
              <div>
                <dt>Comes after</dt>
                <dd className="text-ice">
                  {place.behind} {place.behind === 1 ? 'lesson' : 'lessons'}
                </dd>
              </div>
            )}
            {place.ahead > 0 && (
              <div>
                <dt>Built on by</dt>
                <dd className="text-ice">
                  {place.ahead} later {place.ahead === 1 ? 'lesson' : 'lessons'}
                </dd>
              </div>
            )}
            <div>
              <dt>Verified against</dt>
              <dd className="text-ice">
                {lesson.guide.subject} {lesson.hermesVersion}
              </dd>
            </div>
            <div>
              <dt>Last checked</dt>
              <dd>
                <time dateTime={lesson.updated}>{lesson.updated}</time>
              </dd>
            </div>
          </dl>

          {prerequisites.length > 0 && (
            <div className="border-ice-faint mt-[var(--step)] border-t pt-[calc(var(--step)*0.6)]">
              <p className="font-mono text-ice-dim text-[0.7rem]">Assumes</p>
              <ul className="mt-[calc(var(--step)*0.3)] space-y-[calc(var(--step)*0.2)] text-[0.8125rem]">
                {/* A prerequisite that is still a stub is named but not linked —
                    the dependency is real and worth stating, and a link to a page
                    that does not exist is worse than no link. Same treatment, and
                    the same word, as the module index. */}
                {prerequisites.map((prerequisite) =>
                  isWritten(prerequisite) ? (
                    <li key={prerequisite.id}>
                      <Link
                        href={prerequisite.url}
                        className="underline decoration-[var(--color-rule)]"
                      >
                        {prerequisite.title}
                      </Link>
                    </li>
                  ) : (
                    <li key={prerequisite.id} className="text-ice-dim">
                      {prerequisite.title}{' '}
                      <span className="font-mono text-[0.7rem] text-ice-dim">planned</span>
                    </li>
                  ),
                )}
              </ul>
            </div>
          )}
        </div>
      }
    >
      <article data-pagefind-body>
        <header>
          <p className="font-mono text-ice-dim text-[0.7rem] tracking-[0.06em] uppercase">
            <Link href={`/${lesson.guideSlug}/${lesson.moduleSlug}/`}>
              {String(lesson.moduleNumber).padStart(2, '0')} · {lesson.module.title}
            </Link>
          </p>

          <h1 className="font-display mt-[calc(var(--step)*0.75)] text-[2.375rem] leading-[1.05] tracking-[-0.02em]">
            {lesson.title}
          </h1>

          <p className="text-ice-dim mt-[calc(var(--step)*0.75)] max-w-[62ch] text-[1.125rem] leading-[1.5]">
            {lesson.description}
          </p>

          {/* Below the margin's breakpoint it has nowhere to go, so the parts of it
              that are genuinely load-bearing fall into the flow rather than
              vanishing: what this was checked against, where it sits in the course,
              and the sections it contains. A phone reader is a meaningful minority
              of this audience, not an afterthought. */}
          <div className="mt-[var(--step)] border-t border-ice-faint pt-[calc(var(--step)*0.6)] lg:hidden">
            <p className="font-mono text-ice-dim text-[0.7rem]">
              {place.index} of {place.total} · {lesson.duration} min · verified against{' '}
              {lesson.guide.subject} {lesson.hermesVersion} ·{' '}
              <time dateTime={lesson.updated}>{lesson.updated}</time>
              {place.ahead > 0 && ` · ${place.ahead} later lessons build on it`}
            </p>
            <details className="mt-[calc(var(--step)*0.5)]">
              <summary className="cursor-pointer font-mono text-[0.7rem] text-ice-dim">
                In this lesson ({lesson.headings.length})
              </summary>
              <ol className="mt-[calc(var(--step)*0.35)] space-y-[calc(var(--step)*0.2)]">
                {lesson.headings.map(({ text, slug }, index) => (
                  <li key={slug} className="text-[0.875rem]">
                    <span className="font-mono text-[0.65rem] text-ice-dim">
                      {String(index + 1).padStart(2, '0')}{' '}
                    </span>
                    <a href={`#${slug}`} className="text-ice-dim">
                      {text}
                    </a>
                  </li>
                ))}
              </ol>
            </details>
          </div>
        </header>

        <div className="mt-[calc(var(--step)*0.75)] lg:hidden">
          <LessonProgress id={lesson.id} />
        </div>

        <hr className="border-ice-faint mt-[var(--step)] mb-[calc(var(--step)*1.5)]" />

        <MDXContent code={lesson.mdx} components={mdxComponents} />

        <nav className="border-ice-faint mt-[calc(var(--step)*2.5)] flex justify-between gap-[calc(var(--step)*2)] border-t pt-[var(--step)] text-[0.9375rem]">
          {previous ? (
            <Link href={previous.url} className="max-w-[45%]">
              <span className="font-mono text-ice-dim block text-[0.7rem]">Previous</span>
              {previous.title}
            </Link>
          ) : (
            <span />
          )}
          {next && (
            <Link href={next.url} className="max-w-[45%] text-right">
              <span className="font-mono text-ice-dim block text-[0.7rem]">Next</span>
              {next.title}
            </Link>
          )}
        </nav>
      </article>
    </Page>
    </>
  )
}
